repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.3
    hooks:
      - id: check-github-workflows
        args: [ "--verbose" ]
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.6.0"
    hooks:
      - id: tox-ini-fmt
        args: [ "-p", "lint" ]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.6.0"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.0"
    hooks:
      - id: ruff-format
      - id: ruff
        args: [ "--fix", "--unsafe-fixes", "--exit-non-zero-on-fix" ]
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline' ]
        exclude: (.*/tenant\.sql|.*\.js|.gitlab-ci.yml|uv.lock)


  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [ --skip, "B101", --recursive, clumper ]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
        additional_dependencies:
          - deprecated
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.17
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: [ --strict, --ignore-missing-imports ]
