[tox]
requires =
    tox>=4.2
    tox-uv
env_list =
    lint
    py3{14, 13, 12, 11, 10}

[testenv]
commands =
    pytest -x {posargs:tests --junit-xml=junit.xml -o junit_family=legacy}
    diff-cover coverage.xml --compare-branch=origin/develop --fail-under=100 --exclude version.py
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure
