[tox]
requires =
    tox>=4.2
    tox-uv
env_list =
    lint
    py3{11, 10}-d52-pg
    py3{14, 13, 12}-d{61, 52}-pg
    py3{14, 13, 12, 11, 10}-pg
    py3{14, 13, 12, 11, 10}

[testenv]
deps =
    {d52,d61}: pytest-django>=4.14
    d52: django==5.2
    d61: django==6.1
    pg: psycopg-binary>=2.9.1
extras =
    pg: psycopg
pass_env =
    PGDATABASE
    PGHOST
    PGHOSTADDR
    PGPASS
    PGPASSWORD
    PGPORT
    PGUSER
set_env =
    COVERAGE_OMIT = src/ktcalendars/ranges.py
    pg: COVERAGE_OMIT =
commands_pre =
    python -c "from pathlib import Path; Path('~build/test-results').mkdir(parents=True, exist_ok=True); Path('~build/coverage').mkdir(parents=True, exist_ok=True)"
commands =
    pytest -x {posargs:tests --junit-xml=~build/test-results/junit-{env_name}.xml --cov-report xml:~build/test-results/coverage-{env_name}.xml --cov-report html:~build/coverage/{env_name} -o junit_family=legacy}
    diff-cover ~build/test-results/coverage-{env_name}.xml --compare-branch=origin/develop --fail-under=100 --exclude version.py
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure {posargs}
