# Generated by Django 6.1 on 2026-08-21 13:12

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'period',
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        help_text='N.B.: End date is the day after the actual end date'
                    ),
                ),
            ],
        ),
    ]
