name: Test

on:
  push:
    branches:
      - "**"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-test"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ktcalendars-test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres #pragma: allowlist secret
        ports:
          - 5432:5432
    env:
      PGDATABASE: ktcalendars-test
      PGHOST: localhost
      PGPASSWORD: postgres #pragma: allowlist secret
      PGPORT: 5432
      PGUSER: postgres
    name: Test py${{ matrix.python-version }}
    strategy:
      max-parallel: 1
      matrix:
        include:
          - python-version: "3.14"
            tox-envs: py314,py314-pg,py314-d52-pg,py314-d61-pg
          - python-version: "3.13"
            tox-envs: py313,py313-pg,py313-d52-pg,py313-d61-pg
          - python-version: "3.12"
            tox-envs: py312,py312-pg,py312-d52-pg,py312-d61-pg
          - python-version: "3.11"
            tox-envs: py311,py311-pg,py311-d52-pg
          - python-version: "3.10"
            tox-envs: py310,py310-pg,py310-d52-pg
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
          enable-cache: true
          prune-cache: false
          cache-local-path: ./uv-cache

      - name: Restore cached vEnv
        id: cache-venv-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ./uv-cache
            ./.venv
          key: ${{ runner.os }}-py${{ matrix.python-version }}-venv-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}

      - name: Sync dependencies
        run: uv sync --cache-dir ./uv-cache --frozen

      - name: Save vEnv
        if: steps.cache-venv-restore.outputs.cache-hit != 'true'
        id: cache-venv-save
        uses: actions/cache/save@v4
        with:
          path: |
            ./uv-cache
            ./.venv
          key: ${{ steps.cache-venv-restore.outputs.cache-primary-key }}

      - name: Test
        env:
          UV_CACHE_DIR: ./uv-cache
        run: |
          uv run --cache-dir ./uv-cache \
          tox run -e ${{ matrix.tox-envs }}

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: ~build/test-results/junit-*.xml
        if: ${{ always() }}

      - name: Upload coverage to Codecov
        if: env.CODECOV_TOKEN
        uses: codecov/codecov-action@v4
        continue-on-error: true
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          files: ~build/test-results/coverage-*.xml
          verbose: false
          token: ${{ secrets.CODECOV_TOKEN }}
          name: codecov-${{ github.ref_name }}

      - name: Upload coverage to GitHub (fallback)
        if: env.CODECOV_TOKEN
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.ref_name }}-${{ matrix.python-version }}
          path: ~build/test-results/coverage-*.xml
